package es.usc.citius.servando.calendula.drugdb.model.persistence;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * This class was generated automatically.
 * Please check consistency and completion.
 * Replace {} with the appropriate classes and generate methods as needed.
 */
@DatabaseTable(tableName = "ContentUnit")
public class ContentUnit {

    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_CONTENT_UNIT_ID = "ContentUnitID";
    public static final String COLUMN_NAME = "Name";

    /**
     * Autogenerated ID
     */
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    private Long id;
    @DatabaseField(columnName = COLUMN_CONTENT_UNIT_ID)
    private Long contentUnitID;
    @DatabaseField(columnName = COLUMN_NAME)
    private String name;

    /**
     * Empty constructor, required by ORMLite
     */
    public ContentUnit() {
    }

    public ContentUnit(Long contentUnitID, String name) {
        this.contentUnitID = contentUnitID;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getContentUnitID() {
        return contentUnitID;
    }

    public void setContentUnitID(Long contentUnitID) {
        this.contentUnitID = contentUnitID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
