package es.usc.citius.servando.calendula.drugdb.model.persistence;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * This class was generated automatically.
 * Please check consistency and completion.
 * Replace {} with the appropriate classes and generate methods as needed.
 */
@DatabaseTable(tableName = "Excipient")
public class Excipient {

    public static final String COLUMN_ID = "_id";
    public static final String COLUMN_EXCIPIENT_ID = "ExcipientID";
    public static final String COLUMN_NAME = "Name";

    /**
     * Autogenerated ID
     */
    @DatabaseField(columnName = COLUMN_ID, generatedId = true)
    private Long id;
    @DatabaseField(columnName = COLUMN_EXCIPIENT_ID)
    private String excipientID;
    @DatabaseField(columnName = COLUMN_NAME)
    private String name;

    /**
     * Empty constructor, required by ORMLite
     */
    public Excipient() {
    }

    public Excipient(String excipientID, String name) {
        this.excipientID = excipientID;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getExcipientID() {
        return excipientID;
    }

    public void setExcipientID(String excipientID) {
        this.excipientID = excipientID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
