
/*
 *    Calendula - An assistant for personal medication management.
 *    Copyright (C) 2016 CITIUS - USC
 *
 *    Calendula is free software; you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation; either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    This program is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with this software.  If not, see <http://www.gnu.org/licenses>.
 */

package es.usc.citius.servando.calendula.drugdb.model.persistence;

import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.field.DatabaseField;

/**
*
* This class was generated automatically.
* Please check consistency and completion.
* Replace {} with the appropriate classes and generate methods as needed.
*
*/
@DatabaseTable(tableName = "PrescriptionExcipient")
public class PrescriptionExcipient{

	public static final String COLUMN_ID = "_id";
	public static final String COLUMN_EXCIPIENT_ID = "ExcipientID";
	public static final String COLUMN_PRESCRIPTION_CODE = "PrescriptionCode";

	/**
	* Autogenerated ID
	*/
	@DatabaseField(columnName = COLUMN_ID, generatedId = true)
	private Long id;
	@DatabaseField(columnName = COLUMN_EXCIPIENT_ID)
	private String excipientID;
	@DatabaseField(columnName = COLUMN_PRESCRIPTION_CODE)
	private String prescriptionCode;

	/**
	* Empty constructor, required by ORMLite
	*/
	public PrescriptionExcipient(){}

	public PrescriptionExcipient(String excipientID, String prescriptionCode){
		this.excipientID = excipientID;
		this.prescriptionCode = prescriptionCode;
	}

	public Long getId() { return id; }

	public void setId(Long id) { this.id = id; }

	public String getExcipientID() {
		return excipientID;
	}

	public void setExcipientID(String excipientID) {
		this.excipientID = excipientID;
	}

	public String getPrescriptionCode() {
		return prescriptionCode;
	}

	public void setPrescriptionCode(String prescriptionCode) {
		this.prescriptionCode = prescriptionCode;
	}
}
