
package es.usc.citius.servando.calendula.drugdb.model.persistence;

import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.field.DatabaseField;

/**
*
* This class was generated automatically.
* Please check consistency and completion.
* Replace {} with the appropriate classes and generate methods as needed.
*
*/
@DatabaseTable(tableName = "PrescriptionActiveIngredient")
public class PrescriptionActiveIngredient{

	public static final String COLUMN_ID = "_id";
	public static final String COLUMN_ACTIVE_INGREDIENT_ID = "ActiveIngredientID";
	public static final String COLUMN_PRESCRIPTION_CODE = "PrescriptionCode";

	/**
	* Autogenerated ID
	*/
	@DatabaseField(columnName = COLUMN_ID, generatedId = true)
	private Long id;
	@DatabaseField(columnName = COLUMN_ACTIVE_INGREDIENT_ID)
	private String activeIngredientID;
	@DatabaseField(columnName = COLUMN_PRESCRIPTION_CODE)
	private String prescriptionCode;

	/**
	* Empty constructor, required by ORMLite
	*/
	public PrescriptionActiveIngredient(){}

	public PrescriptionActiveIngredient(String activeIngredientID, String prescriptionCode){
		this.activeIngredientID = activeIngredientID;
		this.prescriptionCode = prescriptionCode;
	}

	public Long getId() { return id; }

	public void setId(Long id) { this.id = id; }

	public String getActiveIngredientID() {
		return activeIngredientID;
	}

	public void setActiveIngredientID(String activeIngredientID) {
		this.activeIngredientID = activeIngredientID;
	}

	public String getPrescriptionCode() {
		return prescriptionCode;
	}

	public void setPrescriptionCode(String prescriptionCode) {
		this.prescriptionCode = prescriptionCode;
	}
}
